eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8060
spring:
  application:
    name: gateway-edge-server

zuul:
  routes:
    microservice1:
      serviceId: FIRST-MICROSERVICE